/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const MessagePlugin: typeof import('tdesign-vue-next')['MessagePlugin']
  const TInput: typeof import('tdesign-vue-next')['Input']
}
