/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
  export interface GlobalComponents {
    CreateTeamDialog: typeof import("./src/components/m-nav/create-team-dialog.vue")["default"];
    MCard: typeof import("./src/components/m-card/index.vue")["default"];
    MCollapsePanel: typeof import("./src/components/m-collapse-panel/index.vue")["default"];
    MContainer: typeof import("./src/components/m-container/index.vue")["default"];
    MCrudTable: typeof import("./src/components/m-crud-table/index.vue")["default"];
    MEmpty: typeof import("./src/components/m-empty/index.vue")["default"];
    MIcon: typeof import("./src/components/m-icon/index.vue")["default"];
    MInfo: typeof import("./src/components/m-info/index.vue")["default"];
    MInfoItem: typeof import("./src/components/m-info-item/index.vue")["default"];
    MMenu: typeof import("./src/components/m-menu/index.vue")["default"];
    MNav: typeof import("./src/components/m-nav/index.vue")["default"];
    MTransition: typeof import("./src/components/m-transition/index.vue")["default"];
    MTransitionRouterView: typeof import("./src/components/m-transition-router-view/index.vue")["default"];
    MyDomainSelector: typeof import("./src/components/my/my-domain-selector.vue")["default"];
    MyEnvRadio: typeof import("./src/components/my/my-env-radio.vue")["default"];
    MyEnvSelector: typeof import("./src/components/my/my-env-selector.vue")["default"];
    MyImageSelector: typeof import("./src/components/my/my-image-selector.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    TAside: typeof import("tdesign-vue-next")["Aside"];
    TAutoComplete: typeof import("tdesign-vue-next")["AutoComplete"];
    TBreadcrumb: typeof import("tdesign-vue-next")["Breadcrumb"];
    TBreadcrumbItem: typeof import("tdesign-vue-next")["BreadcrumbItem"];
    TButton: typeof import("tdesign-vue-next")["Button"];
    TCheckbox: typeof import("tdesign-vue-next")["Checkbox"];
    TCol: typeof import("tdesign-vue-next")["Col"];
    TContent: typeof import("tdesign-vue-next")["Content"];
    TDialog: typeof import("tdesign-vue-next")["Dialog"];
    TDivider: typeof import("tdesign-vue-next")["Divider"];
    TDrawer: typeof import("tdesign-vue-next")["Drawer"];
    TDropdown: typeof import("tdesign-vue-next")["Dropdown"];
    TDropdownItem: typeof import("tdesign-vue-next")["DropdownItem"];
    TDropdownMenu: typeof import("tdesign-vue-next")["DropdownMenu"];
    Team: typeof import("./src/components/m-nav/team.vue")["default"];
    TForm: typeof import("tdesign-vue-next")["Form"];
    TFormItem: typeof import("tdesign-vue-next")["FormItem"];
    TIcon: typeof import("tdesign-vue-next")["Icon"];
    TInput: typeof import("tdesign-vue-next")["Input"];
    TInputGroup: typeof import("tdesign-vue-next")["InputGroup"];
    TInputNumber: typeof import("tdesign-vue-next")["InputNumber"];
    TLayout: typeof import("tdesign-vue-next")["Layout"];
    TLink: typeof import("tdesign-vue-next")["Link"];
    TMenu: typeof import("tdesign-vue-next")["Menu"];
    TMenuItem: typeof import("tdesign-vue-next")["MenuItem"];
    TOption: typeof import("tdesign-vue-next")["Option"];
    TPagination: typeof import("tdesign-vue-next")["Pagination"];
    TPopconfirm: typeof import("tdesign-vue-next")["Popconfirm"];
    TRadioButton: typeof import("tdesign-vue-next")["RadioButton"];
    TRadioGroup: typeof import("tdesign-vue-next")["RadioGroup"];
    TRow: typeof import("tdesign-vue-next")["Row"];
    TSelect: typeof import("tdesign-vue-next")["Select"];
    TSpace: typeof import("tdesign-vue-next")["Space"];
    TSubmenu: typeof import("tdesign-vue-next")["Submenu"];
    TTable: typeof import("tdesign-vue-next")["Table"];
    TTabPanel: typeof import("tdesign-vue-next")["TabPanel"];
    TTabs: typeof import("tdesign-vue-next")["Tabs"];
    TTag: typeof import("tdesign-vue-next")["Tag"];
    TTagInput: typeof import("tdesign-vue-next")["TagInput"];
    TTextarea: typeof import("tdesign-vue-next")["Textarea"];
    TTooltip: typeof import("tdesign-vue-next")["Tooltip"];
  }
}
